import Head from 'next/head';
import { getBaseLayout } from '../features/layouts/base/BaseLayout';
import { PageWithLayout } from '../features/layouts/types/PageWithLayout';
const Home: PageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="bg-gradient-to-r from-cyan-500 to-blue-500">Next app</h1>
      </main>
    </div>
  );
};

export default Home;

Home.getLayout = getBaseLayout;
