import Head from 'next/head';
import { getBaseLayout } from '../features/layouts/base/BaseLayout';
import { PageWithLayout } from '../features/layouts/types/PageWithLayout';
import styles from '../styles/Home.module.css';
const Home: PageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;

Home.getLayout = getBaseLayout;
